### 콘서트 예약
POST localhost:8080/users/1/bookings
Queue-Token: 665f0b3a-4451-4875-b61b-40ec0dd32296
Content-Type: application/json

{
  "seat_id": "1, 2"
}

### 유저 아이디로 예약 목록 조회
GET localhost:8080/users/1/bookings

### 예약 단건 조회
GET localhost:8080/users/1/bookings/1

### 예약 결제
POST localhost:8080/users/1/bookings/1/payment
Queue-Token: 165ffddb-1580-4267-a5f8-0b50fed2e1f5
Content-Type: application/json

### 잔액 조회
GET localhost:8080/users/1/balance

### 잔액 충전
PATCH localhost:8080/users/1/balance
Content-Type: application/json

{
  "balance": 10000
}
